### ISSUE TITLE
Missing Chalk dependency

### ISSUE THREAD

**Issue by arondilbe** [Arthy000/gherkin-testcafe#103]
The package uses chalk but doesn't have it in its dependencies. It causes some incompatibilty if the project importing gherkin-testcafe uses chalk 5.0.1 (and maybe previous versions). 

I managed to get it to work again by adding : 
`"chalk": "4.1.2",` into the dependencies of the package.

**Comment by Arthy000** [comment]
Fix available in 5.5.1
