### ISSUE TITLE
Error generating report 

### ISSUE THREAD

**Issue by kel666** [Arthy000/gherkin-testcafe#104]
Any of the gherkin-testcafe reporter:

gtc-reporter-list
gtc-reporter-minimal
gtc-reporter-spec

are going in error:
` !ERROR The "reportTestDone" method of the "gtc-reporter-minimal" reporter produced an uncaught error. Error details:
TypeError: Cannot read property 'concat' of undefined
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\reporters\gtc-reporter-minimal.js:69:42`

What could it be?

Packages versions:
    "@cucumber/cucumber": "^8.2.2",
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.2.0",
    "@testing-library/user-event": "^14.2.0",
    "@types/file-saver": "^2.0.2",
    "@types/mathjs": "^6.0.11",
    "@types/moment-business": "^0.1.4",
    "@types/node-persist": "^3.1.3",
    "axios": "^0.27.2",
    "eol-converter-cli": "^1.0.8",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^7.2.0",
    "eslint-plugin-prettier": "^3.3.1",
    "fetch-mock": "^9.11.0",
    "gherkin-testcafe": "^5.4.0",
    "glob": "^7.1.6",
    "jest-serializer-html": "^7.0.0",
    "mathjs": "^9.3.0",
    "node-persist": "^3.1.0",
    "prettier": "2.2.1",
    "redux-mock-store": "^1.5.4",
    "serve": "^11.3.2",
    "swagger-typescript-api": "^4.4.0",
    "testcafe": "^1.18.6",
    "testcafe-browser-provider-selenium": "^1.2.0",
    "testcafe-reporter-junit": "^3.0.2"

Tnx a lot
Fabio

**Comment by Arthy000** [comment]
Hi @kel666 
Could you please have a look at #89? I think you are experiencing the same issue

**Comment by kel666** [comment]
Tnx for the quick reply.

I updated to 5.4.4 but now I have this:

`C:\git\USP.Commodity.UI>npx gherkin-testcafe --skip-js-errors --compiler-options typescript.options.esModuleInterop=true chrome --reporter gtc-reporter-list src/e2etest/**/*.ts src\e2etest\bookingBullet.feature
ERROR Cannot prepare tests due to the following error:

TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at getDefinitionLineAndUri (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\get_definition_line_and_uri.ts:25:18)
    at SupportCodeLibraryBuilder.defineStep (C:\git\USP.Commodity.UI\node_modules\@cucumber\cucumber\src\support_code_library_builder\index.ts:153:50)
    at Object.<anonymous> (C:\git\USP.Commodity.UI\src\e2etest\steps.ts:37:1)
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:269:26
    at C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:268:17
    at GherkinTestcafeCompiler._loadStepDefinitions (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:273:5)
    at GherkinTestcafeCompiler.getTests (C:\git\USP.Commodity.UI\node_modules\gherkin-testcafe\src\compiler.js:142:5)`

**Comment by Arthy000** [comment]
Did you make sure to match the peer dependencies?
"peerDependencies": {
    "@cucumber/cucumber": "^8.0.0",
    "@cucumber/cucumber-expressions": "^15.0.0",
    "testcafe": "~1.20.0"
},

If updating to TestCafe 1.20 is a deal breaker for you, you can downgrade this package to version 5.4.3 which is compatible with TestCafe 1.18

**Comment by kel666** [comment]
Same error specifying deps you suggested.

Anyway I tried with 5,4,3 and it's working!

tnx
Fabio
