### ISSUE TITLE
Load config when tags used

### ISSUE THREAD

**Issue by mokone91** [Arthy000/gherkin-testcafe#105]
Hi! I need to split my test by tags, but i noticed that if i want to use tags - i should provide browser name and tests path also, even if its configured in .testcaferc

I have just regular test command: 
package.json
```
  "scripts": {
    ...
    "test:e2e": "gherkin-testcafe", 
    }
 ```
 
 So i want to tag all my tests with 'v1' and then add:
 package.json
```
  "scripts": {
    ...
    "test:e2e": "gherkin-testcafe", 
    "test:e2e: v1": "gherkin-testcafe --tags v1" , 

    }
 ```
But i getting 
`
ERROR Cannot find the browser. "--tags" is neither a known browser alias, nor a path to an executable file.
` 

its can be fixed by passing browsername and testts path, but i already have this configured in  .testcaferc and i do not whant to duplicate this

Is this possible to fix?

**Comment by Arthy000** [comment]
Hi @mokone91, I'll have a look

**Comment by Arthy000** [comment]
Hi @mokone91 
I finally managed to reproduce your issue by using an older version of TestCafe.

Starting from version 1.20.0 it seems to work as expected.
Use the newly added [compatibility matrix](https://github.com/Arthy000/gherkin-testcafe/blob/master/version-matrix.md) to select your versions of TC/GTC
