### ISSUE TITLE
Scenario details in before hook

### ISSUE THREAD

**Issue by csurfleet** [Arthy000/gherkin-testcafe#109]
I'm trying to access the name of the scenario being executed from the before hook. I see that cucumber can pass the scenario into its before hooks:
https://stackoverflow.com/questions/51746919/how-to-get-scenario-name-from-cucumber-js

Is there any way to access this through the TestController object we are given in your before hook?

**Comment by Arthy000** [comment]
Hello @csurfleet,

I tried a few things, like using [`t.testRun.name`](https://stackoverflow.com/questions/52087065/access-the-name-of-the-current-fixture-and-test-at-runtime). Howere it seems that even though I'm correctly calling the testbuilder from TestCafe with the test name as its first parameter, the testcontroller never gets the value, and the property remains undefined. IDK if it is a bug on TC's side or if I'm missing something, but I couldn't find anything.

Might I ask for a use case though? Never really had a need for it, and the feature is so poorly documented on TC's side that [they didn't even bother to make it part of the TestController type](https://github.com/DevExpress/testcafe/issues/2826#issuecomment-524377039)
This makes me think there might be an easier way to do what you want.

**Comment by eroetman** [comment]
Here is an example that works for us, but I'm not sure if this is what you need:

`Before("@example", async (t) => {
  const controller: any = t;
  const feature = controller.testRun.test.testFile.currentFixture.name;
  const scenario = controller.testRun.test.name;
  console.log(feature, scenario);
});`

**Comment by Arthy000** [comment]
@eroetman thanks for your help :) 
I'm adding some properties to the declaration of TestController on GTC, so some properties are accessible without casting. Available whenever I release a new version.
@csurfleet I'm closing this issue
