### ISSUE TITLE
How to integrate gherkin-testcafe?

### ISSUE THREAD

**Issue by leonleo997** [Arthy000/gherkin-testcafe#11]
Hey there,
I would like to integrate sauce labs with this library, does anyone know if there is a way to do that?

Thank you

**Comment by Arthy000** [comment]
Hello,

The role of this package is just to provide a way to define testcafe scenario in gherkin. 
As such, using SauceLabs with gherkin-testcafe boils down to using SauceLabs with testcafe itself. 

I don't use SauceLabs myself, but from what I see there is an addon for testcafe that allows your tests to run in saucelabs:
https://github.com/DevExpress/testcafe-browser-provider-saucelabs

All you have to do is install the addon (follow their documentation), then you can use it with gherkin-testcafe like almost li:
`gherkin-testcafe "saucelabs:Chrome@beta:Windows 10" "path/to/*.js" "path/to/*.feature"`

PS: As a rule, any command and addon from testcafe will work with gherkin-testcafe simply by
1. replacing `testcafe` with `gherkin-testcafe` in command lines
2. adding the path to the .feature file(s)

**Comment by leonleo997** [comment]
Thank you, it works!
