### ISSUE TITLE
Upgrade Gherkin-Testcafe library to support the latest version of Testcafe

### ISSUE THREAD

**Issue by nixmove** [Arthy000/gherkin-testcafe#129]
Hi,

I hope this message finds you well. I was wondering if there are any plans to upgrade the Gherkin-Testcafe library to support the latest version of Testcafe, which is currently at v2.5.0? I believe that this upgrade would be beneficial for our testing processes and would help us to take advantage of the latest features and improvements in Testcafe.

Please let me know if there are any plans in the works, or if this is something that we can request as a future enhancement. Thank you for your time and assistance.

**Comment by Arthy000** [comment]
Hi @nixmove 

This is planned already, it should arrive soon :)

**Comment by nixmove** [comment]
Great :) Thank you

**Comment by Arthy000** [comment]
No worries :)

Just so you know, you don't have to meet the peer dependencies, if you don't you just get a warning. (but doing so might break something, you cannot be sure until you try)
In this instance, I was able to use versions 2.4 and 2.5 without a single code change, so you would have been able to use GTC 6.0.0 with TC 2.5.0

Anyway, version 6.0.1 has been released and officially supports TestCafe 2.4.0 and 2.5.0 without warnings
