### ISSUE TITLE
Compatibility with testcafe 2.5.0 and Cucumber 9.1.0

### ISSUE THREAD

**Issue by bbutel** [Arthy000/gherkin-testcafe#130]
Is that possible to upgrade gherkin-testcafe to be compliant with last version of testcafe and cucumber please.

thx a lot

**Comment by Arthy000** [comment]
Hi @bbutel 

Yes, it's coming soon :)

**Comment by bbutel** [comment]
great news.
thx a lot

**Comment by Arthy000** [comment]
Hello again,

Just released version 6.0.1 that explicitely supports TC 2.5, however I didn't include the cucumber so people that only want to update TC can.

I'll start working on the cucumber update right away.

**Comment by Arthy000** [comment]
Version 7.0.0 is out (nothing to change really, looks like there weren't many breaking changes between cucumber 8 and 9)

**Comment by bbutel** [comment]
Ho thx a lot for your action. You're so speed :)
