### ISSUE TITLE
[Audit] Upgrade testcafe to v3.2.0

### ISSUE THREAD

**Issue by digiacomo-a** [Arthy000/gherkin-testcafe#139]
Hi, when i run npm audit looks like we have 5 moderate severity vulnerabilities with testcafe v3.1.0.
Could be nice to open a PR and upgrade it, not sure how much breaking changes are in this version, but I can contribute on it.

**Comment by Arthy000** [comment]
Hi @digiacomo-a, version 7.1.1 is available and compatible with TC 3.2.0

Not sure if you are aware, but there is in fact nothing stopping you from trying to use TC 3.2 with GTC 7.1.0 (and it would in fact have worked => if you take a look at the changes linked to this issue, you'll see that I made no code change)
You'd get a warning at the installation, or worse case scenario you'd need to find the flag/option to ignore the peer dependency incompatilibity.

One day when you try to use a newer version of TC and it doesn't work with the latest version of this package, then it could be the sign of a breaking change.

All this to say, I don't usually release a new version with so little changes, so you might be better off ignoring the peer dependency warning if you really need the newest TC version

**Comment by soletan** [comment]
Just tried it. npm rejects to install Testcafe 3.2 or even 3.1 with 7.1.1 of your package. I think there is an issue with your definition of supported peer dependencies. Just tried https://semver.npmjs.com/ using **testcafe** and what is in your package.json given for the peerDependencies. The result is listing 2.x versions of testcafe as matches, only. My guess: the caret has to be removed.

**Comment by Arthy000** [comment]
You're right, I think it stopped working properly when the upper range became version 3, and I didn't even realise
Solved with version 7.1.2
