### ISSUE TITLE
 multiple browser windows support --disable-native-automation

### ISSUE THREAD

**Issue by hannilec** [Arthy000/gherkin-testcafe#143]
Hi, 
I try to run a test using multiple windows -> using switchToWIndow (https://testcafe.io/documentation/402677/reference/test-api/testcontroller/switchtowindow)
but when I add --disable-native-automation option to run the test it opens the browser but then the test doesn't continue.

**Comment by Arthy000** [comment]
Hello @hannilec 

What version of TestCafe and Gherkin-Testcafe are you using?
Have you tried running a similar test in vanilla TC?

TBH it looks like a pure TestCafe issue, and it might be fixed in other versions.

**Comment by Arthy000** [comment]
Closing this issue, feel free to reopen if you still want me to investigate
