### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by mworkc** [Arthy000/gherkin-testcafe#21]
I'm getting this error `env: node\r: No such file or directory` on version 2.5.2 and higher.

It appears certain files are now using DOS style linefeed (CRLF) instead of LF.

To get this working on a Mac I had to convert the files in /node_modules/gherkin-testcafe to LF.

**Comment by Arthy000** [comment]
Hello,

I'll try to fix this soon

**Comment by Arthy000** [comment]
Hi @mworkc,

Sorry it took so long, but it should be alright now
