### ISSUE TITLE
Cucumber is deprecated (use @cucumber/cucumber instead)

### ISSUE THREAD

**Issue by sgarfinkel** [Arthy000/gherkin-testcafe#22]
Fixing this will unfortunately require renaming any import or require to use the new package name.

**Comment by Arthy000** [comment]
Hello, 

Is this a warning you get while using the package or are you just telling me?
I'm well aware that some of the dependencies in this package are outdated, but as long as it works for the latest version of TestCafé I don't think there is any need to update.

**Comment by sgarfinkel** [comment]
This is a warning that all users will get whenever they install the peer dependency.

**Comment by Arthy000** [comment]
I see.
I'll try to update the dependency (the actual dependency), but I'm not sure it's even required. I'd say that the only changes that are really necessary are the peer dependency in the package.json and the documentation.

**Comment by sgarfinkel** [comment]
According to the warning they changed the namespace for imports too.

**Comment by Arthy000** [comment]
I think you misunderstood, what I meant is that I do not really need to change the dependency in gherkin-testcafe:
- it is a devDependency, so it does not concern the final user
- the original package still exists, it won't be updated anymore, 

=> I will update documentation and peerDependency, allowing users of this package to use the newest cucumber in their project, and will stop there at the moment 
(a massive update in dependencies/devDependencies is coming anyway)

**Comment by sgarfinkel** [comment]
At runtime won't this throw an exception https://github.com/Arthy000/gherkin-testcafe/blob/develop/src/compiler.js#L6 due to the change from `require('cucumber')` becoming `require('@cucumber/cucumber')` in the new releases?

**Comment by Arthy000** [comment]
Well it should not, and does not from what I see when I use it.
The reason being that cucumber will only throw that warning with the latest cucumber (7.something), and the current cucumber in this package is 5.something.

**Comment by thelazurite-cell** [comment]
Do you guys need help with upgrading the package to the newer version of cucumber? I just did this in my own personal version would be happy to help

**Comment by Arthy000** [comment]
Hello,
You can submit a PR and I'll review it :)
(please use [commitizen](https://github.com/Arthy000/gherkin-testcafe#contributing) to generate your commit message, it'll generate a proper changelog and make it easier to release a newer version later on)
TBH it's not that hard, it just doesn't seem necessary, and as I'm alone maintaining this project I haven't gotten to it yet.

Thanks for offering your help :D

**Comment by thelazurite-cell** [comment]
No problem @Arthy000 :) I was stuck when I needed to upgrade my version of testcafe to 1.10, and I found this repo and it helped me out a lot, so I'd like to help out where I can to share the knowledge.
