### ISSUE TITLE
How to share data between step definitions?

### ISSUE THREAD

**Issue by dskochubey** [Arthy000/gherkin-testcafe#26]
Is there an example, how to share data between step definitions?

**Comment by Arthy000** [comment]
Hello,

Sorry I took that long to answer. 
To share data between steps:
- you can use variables
```js
let sharedValue;
Given(/some regex/, async(t) => {
  sharedValue = 10;
});

When(/some other regex/, async(t) => {
  console.log(sharedValue);
});
```
**Warning**; This will only work if your steps are defined in the same .js/.ts file.
- you can use t.ctx ([test context](https://devexpress.github.io/testcafe/documentation/reference/test-api/testcontroller/ctx.html))
This is more robust as it works regardless of the organization of you test definition.

However, IMO you should try to keep steps as isolated as possible, including data sharing (it's just an advise, and it's not always possible to avoid sharing data between steps, but sharing too much between steps quickly becomes a source of confusion)

**Comment by dskochubey** [comment]
Thank you, @Arthy000. 
I was a bit confused at the beginning because CucumberJS recommends using `World.`

It is nice that regular `t.ctx` is available to share state between steps.
