### ISSUE TITLE
Overriding step definitions

### ISSUE THREAD

**Issue by raj-balaebail** [Arthy000/gherkin-testcafe#36]
I am trying to implement an inheritance/override model where I want to have a 'generic' step definition which will be imported in and specific steps overridden as necessary.

I was able to import the step definitions from my generic file, but the override (I used the same step definition name) seems to not be overriding the step definitions.
ex:
Generic file
```
Given('User navigates to x page', async () => {
  await pAPage.navigateTo('x')
});
```
Specific/inherited file
```
Given('User navigates to x page', async () => {
  await pAPage.navigateTo('y')
});
```

PS: Our software has a number of applications that are all similar but vary a bit from the base configuration based on the client. Having to define the common steps multiple times will create a maintenance nightmare down the road. Hence we want to group the common step definitions in the generic file and import and override in client specific step definition file as needed.

Appreciate all the help in advance.

**Comment by Arthy000** [comment]
Hello :)

The package will use the first matching step it finds. This means that if you want to have an overwrite system, the specific step files should be loaded before the generic step file.

`gherkin-testcafe firefox ./currentapp/steps/*.js ./global/steps/*.js ./global/*.feature`
or something like that.

I've used this system in a personal repo and it works (though I used the API, not the CLI)

Let me know if it helps.

**Comment by raj-balaebail** [comment]
Is there a way to implement dependency injection, as I need the generic steps to be able to reference my specific page objects ? If you know of an example, that would be helpful !!

**Comment by raj-balaebail** [comment]
Another problem that I am running in to is that my application has several pages that I have set up in the page object model of one class per page. If I have a common step such as click an element, I will have to implement that for every page (and make those steps distinguishable) as I need the reference to the page object in order to pull in the right selector. 

This problem only manifests if I want to run all my tests across all pages. Presumably if I can implement dependency injection, I can solve this problem too.

**Comment by raj-balaebail** [comment]
I just solved this !! I will post the solution in a bit.

**Comment by Arthy000** [comment]
@raj-balaebail I'd be curious to see how you did it, because I'm not sure I completely understand the organization of your project :)
