### ISSUE TITLE
step definition inheritance

### ISSUE THREAD

**Issue by raj-balaebail** [Arthy000/gherkin-testcafe#40]
Building on https://github.com/Arthy000/gherkin-testcafe/issues/36 I had partially solved the loading order problem. However, I am running in to trouble when I try to scale it further.

Following is a simplification of the adopted structure:
```
PageObjects - 
  global/globalObject.js
  local/Page1Object.js
  local/Page2Object.js
StepDefinitions - 
  global/globalStep.js
  local/Page1Step.js
  local/Page2Step.js
Tests - 
  Page1.feature
  Page2.feature
```
For PageObjects, Page1Object and Page2Object inherit from globalObject and extend it by adding their own methods. Hence, all the elements/methods for Page1 is eventually defined in Page1Object.
Similarly, I want to set up StepDefinitions, Page1Step and Page2Step to inherit from globalStep. I got this working by creating a class for global step and importing after defining all the steps in Page1Step.
ex: globalStep.js
```
import { Given, When, Then } from '@cucumber/cucumber'

export default class GlobalStep {
  constructor(page) {
    When('user clicks {word}', async (t, [element]) => {
      await page.clickElement(page[element])
    });
```
and Page1Step.js
```
import { Given, When, Then } from '@cucumber/cucumber'
import GlobalStep from '../global/globalStep'
import Page1Object from '../../PageObjects/local/Page1Object'
const page = new Page1Object()
....Define specific given/when/then that need to load first...
const p1Step = new GlobalStep(page)
```
Essentially implementing dependency injection by passing in the object to global step. This works well when I inherit/run the feature file for that page.

If I run the specific files ex: `gherkin-testcafe firefox ./steps/**/Page1Step.js ./tests/Page1.feature` or `gherkin-testcafe firefox ./steps/**/Page1Step.js ./tests/Page1.feature` they both work, but the moment I try to run all test files together ex:
`gherkin-testcafe firefox ./steps/**/*.js ./tests/*.feature` the Page2.feature tests all fail. This is because when I run the Page2.feature file, it is still loading the Page1Step first, which calls the globalStep with page1Object, which doesn't have the elements needed (which are defined in Page2Object). 

@Arthy000 Would appreciate your thoughts. I am unsure on how to easily run all tests correctly, as the order of steps to be called will vary based on the test file to be run.

Note: I use this approach as I want to have common steps such as  user clicks  element  in  a global file and use dependency injection to pass the right page object.

**Comment by raj-balaebail** [comment]
An approach that I tried, but it failed (although in theory it should work) was to load the global step as a BeforeAll in page1Step. However that didn't seem to link the steps in global step at runtime.

**Comment by raj-balaebail** [comment]
Solved this issue !!
Had to create the object in t.ctx context as part of the first step in my local step and use that object in my global step.

ex: globalStep.js
```
import { Given, When, Then } from '@cucumber/cucumber'

export default class GlobalStep {
  constructor() {
    When('user clicks {word}', async (t, [element]) => {
      await t.ctx.page.clickElement(page[element])
    });
```
and Page1Step.js
```
import { Given, When, Then } from '@cucumber/cucumber'
import GlobalStep from '../global/globalStep'
import Page1Object from '../../PageObjects/local/Page1Object'
const page = new Page1Object()

Given('user navigates to home page', async (t) => {
  t.ctx.page = new Page1Object()
  await t.ctx.page.navigateTo(t.ctx.page.home)
});
const p1Step = new GlobalStep()
```

**Comment by Arthy000** [comment]
Hi @raj-balaebail 

Interesting solution!
Another would be to have steps with different names (using a Scenario Outline with examples, for instance) and a common helper function that receives a parameter to change the pagemodel it uses.

```gherkin
Scenario Outline: your test name
  Given user navigates to <name> page

  Examples:
  |  name  |
  |  home  |
  |  other  |
```

```ts
Given('user navigates to (.+) page', async(t, name) => {
  const pageModels = { home: new Page1Object(), other: new Page2Object() };
  t.ctx.page = pageModels[name];
  await t.navigateTo(t.ctx.page.home)
})
```

As you loaded the pagemodel in the context, it is available for all the steps in your test, so I am also not sure you need your global steps to 

I do have a question for you: why did you add the `click` and `navigateTo` functions to your pagemodel?
Unless you customized them, you should use `t.click` and `t.navigateTo`: it would make your tests easier to read, and you already receive t as a parameter in all your step functions so you don't have much to change.

**Comment by raj-balaebail** [comment]
@Arthy000 For steps such as click on a button, I want to have one step (in the spirit of DRY) where we figure out the right pagemodel which has the right selectors. Our project has to deal with multitude of scale in the sense that we sell similar yet bespoke products for our clients. 
ex: We have 10 clients who subscribe to 2 products on average and each product has 6 applications. There is 90% commonness between all the applications, but there is 10% on an average (and it isn't the same 10% across clients) that is custom.
Hence I want to avoid creating 1000s of steps which all essentially perform click on a button. That was the main idea for a global common step, that should inherit the right page model and selector at run time. This way I only have 1 step per action for all partner/product/application. 
All my page objects inherit from a testcafe layer where I control some custom actions based on parameters. For example, navigateTo gets some arguments that change its behavior (other than the default).
All in all, the framework I am designing tries to take DRY to the extreme to reduce duplication and hopefully avoid maintenance issues.

**Comment by Arthy000** [comment]
Very nice! Thanks for clarifying. Looks like you're all good now so I'll close this issue :)
