### ISSUE TITLE
Unmaintained gherkin version

### ISSUE THREAD

**Issue by aslakhellesoy** [Arthy000/gherkin-testcafe#46]
Hi, I see you're using the [unmaintained version of gherkin](https://github.com/Arthy000/gherkin-testcafe/blob/f9a43a65802929267428f6e9fa5fbf6b20cec5e6/package.json#L48).

You should probably upgrade to `@cucumber/gherkin`

**Comment by Arthy000** [comment]
Hi @aslakhellesoy, thanks for the heads up, I knew my dependency was quite outdated but not that the package had been moved. I'm fixing this.
