### ISSUE TITLE
Feature file lines are not visible in console

### ISSUE THREAD

**Issue by umerhamdan10** [Arthy000/gherkin-testcafe#48]
![image](https://user-images.githubusercontent.com/43927146/121032464-93ec3d00-c7ab-11eb-837b-72da68d2cdc5.png)

Only the scenario line show in the console. Is it possible to show  successfull line in console at run time?

**Comment by Arthy000** [comment]
Hello.
Sadly, that's actually testcafe showing the name of the test, not gherkin-testcafe. 
To display the steps, we would need to add the whole scenario to the test name, not just the scenario title. But even then it would display the whole name at once, not successful steps when they finish running.

**Comment by Arthy000** [comment]
There may be a way to do this with a custom testcafe reporter, but that would require some modifications in this package anyway. And it would be a custom that would not be compatible with vanilla testcafe so it would need to be included in this package, and not standalone.

Console.log is more of an incomplete workaround because it would not get included if you wanted to have your report in a file instead of the console.

And then you would probably want to do this for each type of report (TeamCity, JSON, XML, plain text, ...).

All this to say that I don't really have the time to do this in the foreseeable future, but you are welcome to try.

**Comment by kmrozConfigit** [comment]
> runScenario

Hi, could you expline morem how to use this snipped and get at least text of steps ?

**Comment by kmrozConfigit** [comment]
> I have done something like this, but from what I can tell there doesn't seem to be a way/easy way to get the step type (given/when/then/etc.)
> 
> ```
>     protected async runScenario(scenario: messages.Pickle, error: Error, ...params: ExecutorSpecificParams): Promise<Error> {
>         try {
>             for (const step of scenario.steps) {
>                 await this.resolveAndRunStepDefinition(<messages.Pickle.PickleStep>step, ...params).catch(reason => error = reason);
>                 if (error) {
>                     console.log(`${ConsoleColor.FgRed}\t${symbols.err} ${scenario.name} - ${step.text} ${ConsoleColor.Reset}`);
>                     break;
>                 } else {
>                     console.log(`${ConsoleColor.FgGreen}\t${symbols.ok} ${scenario.name} - ${step.text} ${ConsoleColor.Reset}`);
>                 }
>             }
>         } catch (e) {
>             error = e;
>         }
> 
>         return error;
>     }
> ```

Hi, could you explain more, how to use this snipped and get at least text of steps ?

**Comment by Arthy000** [comment]
hello @umerhamdan10 
IDK if you are still interested but I finally started working on this yesterday, and the results are promising.

**Comment by Arthy000** [comment]
New version 5.4 released, includes 3 custom reporters (`gtc-reporter-spec`, `gtc-reporter-list` and `gtc-reporter-minimal`)
=> `gtc-reporter-spec` is used by default so if you didn't explicitly set a reporter you'll get the new behavior as soon as you update.

Steps and the index of the failed step are included in the metadata, so you can create/adapt your own reporter to display the steps information.
Testcafé's json reporter already includes the metadata for the tests so no change needed on my part.
Full documentation [here](https://github.com/Arthy000/gherkin-testcafe#step-reporting)
