### ISSUE TITLE
Generate *.json with cucumber steps

### ISSUE THREAD

**Issue by Sabou44** [Arthy000/gherkin-testcafe#50]
Hi,

I would like to know how I can generate a *.json with cucumber steps to be used in multiple-cucumber-html-reporter like this

I my example, the current *.json have been generate with:

```
cucumber-js features/ -f json:reports/report.json
```

Thanks

![Capture](https://user-images.githubusercontent.com/59806062/122588455-67fc7180-d05f-11eb-998a-437f6d22d927.PNG)

**Comment by Arthy000** [comment]
Hi there,
This is a complicated mater :(
In testcafe there is no "step", thus no real way to detect when a step completed successfully (or not) => #48 
Also, there is a TestCafe reporter that generates JSON files that are compatible with `multiple-cucumber-html-reporter`, but it won't include steps at all, for the same reason => #25

I guess implementing a tool that takes the `.feature` and outputs a `.json` with all the steps is possible (but without the notion of success/failure, juste a listing of scenarios and attached steps) but that's kinda out of the scope of this package.

**Comment by Sabou44** [comment]
Hi,

This is so sad :'(

I understand better why I hadn't managed to find an example yet.

If ever the subject motivates some people, I think I'll have to dig into it so any goodwill will be welcome ;)

**Comment by Sabou44** [comment]
Hi,

I think I found a good lead with this project I put this here for those who have the same problem:

https://github.com/alexej-strelzow/testcafe-cucumber-typescript
