### ISSUE TITLE
Lack of transpose function from Cucumber DataTable

### ISSUE THREAD

**Issue by bartchie** [Arthy000/gherkin-testcafe#52]
Hello,

I'm getting error when I try to use transpose function on DataTable type object from cucumber.
Property 'transpose' does not exist on type 'DataTable'.
And this is happening only in v5.0.1. When I reverted to v5.0.0, everything is ok.
I also saw, that in index.d.ts ,there is DataTable interface without transpose function, which actually exists in @cucumber/cucumber.

**Comment by Arthy000** [comment]
Sorry for the delay, I'll have a look

**Comment by Arthy000** [comment]
Hello again, I just published a new version, your issue should be solved.
