### ISSUE TITLE
Not able to debug the automation tests with gherkin-testcafe npm ? 

### ISSUE THREAD

**Issue by samplehub** [Arthy000/gherkin-testcafe#53]
Hi , 

I have created Testcafe +BDD + Typescript framework with gherkin-testcafe npm in vscode. 

I am able to run the feature files with gherkin-testcafe commands but not able to debug .
https://github.com/kiwigrid/gherkin-testcafe

 Please let me know what is the config file we need to use in launch.json 

This is not working for me . 
https://testcafe.io/documentation/402800/recipes/debugging/visual-studio-code

```

{
    "type": "node",
    "protocol": "inspector",
    "request": "launch",
    "name": "Launch test files with TestCafe",
    "program": "${workspaceRoot}/node_modules/testcafe/bin/testcafe.js",
    "args": [
        "firefox",
        "${relativeFile}"
    ],
    "console": "integratedTerminal",
    "cwd": "${workspaceRoot}"
}
```

**Comment by samplehub** [comment]
Please any reply. @Arthy000 . Thanks

**Comment by Arthy000** [comment]
Hello @samplehub,

Sorry for the delay, things have been crazy at work.

THB I've never used VSC debug, I use the debug option from TestCafe. So I'm not really an expert, but I think the "program" line might need to be adapted to target gherkin-testcafe instead, but I'm not sure at all :/

**Comment by lobmailz** [comment]
@samplehub try:

`"program": "${workspaceRoot}/node_modules/gherkin-testcafe/main.js", with no args (if you have .testcaferc.json)`

I just tried and it worked for me.

**Comment by Arthy000** [comment]
Thank you @lobmailz
