### ISSUE TITLE
Support for Doc String type

### ISSUE THREAD

**Issue by d4niloArantes** [Arthy000/gherkin-testcafe#64]
Hi! I couldn't find any news about this subject. I did find this [issue](https://github.com/kiwigrid/gherkin-testcafe/issues/51) and this [PR](https://github.com/kiwigrid/gherkin-testcafe/pull/69) in the archived repository but no results.

It still returning null when I try something like
```
Then('a warning tile will display the following message:', async (t, [], docString) => {
    console.log(docString);
});
```

**Comment by Arthy000** [comment]
Hi @d4niloArantes,
I'll have a look :D

**Comment by Arthy000** [comment]
Hello again!
Looks like it's done, actually:
The first argument of your function is the TestController.
The second argument is the array containing the parameters from your feature.
The third argument is the data table (that's what's `null` in your example)
The fourth argument is the doc string :D

```ts
Given(`Some step name`, async (t: TestController, ...rest) => {
  console.log('output:', rest);
});

```
```
output: [ [], null, 'This is my doc string\nIt works' ]
```

**Comment by d4niloArantes** [comment]
Thank you so much @Arthy000. I was using the `4.0.0` version and it only works for `5.0.0` or above. 
Could you add this examples in the examples folder please?

```
#docstring.feature
Feature: Doc string demo feature

  Scenario: Asserting page subtitle
    Given I open TestCafe demo page
    Then I see the following page subtitle
      """
      This webpage is used as a sample in TestCafe tutorials.
      """

# this only works for v5.0.0 or above
```

```
// docstring.js
import { Given, Then } from '@cucumber/cucumber';
import { Selector } from 'testcafe';

Given('I open TestCafe demo page', async t => {
    await t
        .navigateTo('https://devexpress.github.io/testcafe/example/');
});

Then('I see the following page subtitle', async (t, [], dtTable, docString) => {
    await t
        .expect(Selector('header > p').textContent).contains(docString);
});
```

While I was updating my Cucumber and gherkin-testcafe versions, I faced several problems and the versions that worked were:
```
"dependencies": {
    "@cucumber/cucumber": "^7.3.1",
    "gherkin-testcafe": "^5.0.0",
    "testcafe": "^1.14.2"
  }
```

**Comment by Arthy000** [comment]
I was planning to add an example, thanks for providing it :)
Regarding the dependencies of your projet, I'd advise to upgrade to the latest version of this package (5.1.0) and upgrade TestCafe itself to match the version required by gherkin-testcafe (>= 1.15.2)
