### ISSUE TITLE
Support complex tag expressions

### ISSUE THREAD

**Issue by combmag** [Arthy000/gherkin-testcafe#7]
Hello,

Currently gherkin supports only `AND` syntax to run specific tags. Is there a way currently to support advanced tag expressions like: `(@smoke or @ui) and (not @slow)`?

Thanks

**Comment by Arthy000** [comment]
Hello,

For your example, you can use
--tags "@smoke, @ui, ~@slow"

Basically, if you only use commas, 
"@tag1, @tag2, ~@tag3, ~@tag4"
Will translate to "has tag1 OR tag2 AND NOT tag3 or tag4"

However, if you need two tags both present on your scenario, I added a AND operator a while back:
--tags "@tag1 and @tag2"
(https://github.com/kiwigrid/gherkin-testcafe/pull/57)

**Comment by Arthy000** [comment]
I made some modifications to the doc, don't hesitate to ask if you need more help
