### ISSUE TITLE
Run tests via Scenario name

### ISSUE THREAD

**Issue by jcroma** [Arthy000/gherkin-testcafe#73]
Hello there! It is more like question instead of issue.
Since `gherkin-testcafe` is working on cucumberJS and cucumberJS allows to run only specific `Scenario` by adding line of scenario to runner will be that possible in gherkin-testcafe in future ? 
Adding cucumberJS syntax example: https://github.com/cucumber/cucumber-js/blob/v3.0.1/features/target_specific_scenarios_by_line.feature
And also:
https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md#running-specific-features
```Specify a scenario by its name matching a regular expression
$ cucumber-js --name "topic 1"
$ cucumber-js --name "^start.+end$"
If used multiple times, the scenario name needs to match only one of the names supplied
To escape special regex characters in scenario name, use backslash e.g., \(Scenario Name\)```

**Comment by Arthy000** [comment]
Hey @jcroma, 
I had no idea this feature even existed, I'll look into it.

I have to be honest though, I don't see how this is better than filtering by name of the scenario (which is a feature that's already available through TestCafe's test filtering)
![image](https://user-images.githubusercontent.com/1800622/155302499-7bf06ec8-84a9-47ae-b233-c3f5458af243.png)
(this is the output of `gherkin-testcafe -h`)
