### ISSUE TITLE
Access a page under basic Auth

### ISSUE THREAD

**Issue by kabomi** [Arthy000/gherkin-testcafe#76]
Hi all, 

I need to access a page that's behind basic auth. So I have to set httpAuth credentials probably at [fixture level](https://testcafe.io/documentation/402781/reference/test-api/fixture/httpauth)

But, I couldn't find a command line argument that I could pass on for that purpose.
Any ideas on how can I set the httpAuth credentials?

In the meantime, I'm going to give it a try with a [proxy configuration](https://testcafe.io/documentation/402638/reference/configuration-file#proxy)

Cheers

**Comment by Arthy000** [comment]
Hi @kabomi 
I'm very sorry about the long delay (regarding your other ticket that you closed), I was travelling abroad and wasn't really paying attention to my emails.

I could easily add the ability to use command line to authenticate, something like 
```
--username <string> --password <string> [--domain <string> [--workstation <string>]]
```

However, that would make writing your command line pretty annoying (even if you only use the mandatory ones). 
So a better option is to use a configuration file in your repo, and on my side create a single command line parameter
```
--useHttpAuth
```

The only thing that's left is figure out how to attach the credentials to a specific feature (to match normal TestCafe behavior).
ATM the only idea I got is to create a JSON file like:
```json
[
  "features": ["name1", "name2"],
  "username": "your username",
  "password": "your password",
  "domain": "your domain, can be undefined",
  "workstation": "your workstation, can be undefined"
]
```
But this could also be a pain to maintain if you have many features or many credentials. 

What do you think?

**Comment by kabomi** [comment]
Hi @Arthy000 
Now I have to apologize too, sorry my lack of response!

My use case is: A fixture with only one set of credentials, other fixtures that does not need them.
So, your idea with the json file would be sufficient.

Another idea could be to generate a file for every .feature file that needs credentials, like:
- For a file named `stage.feature` creating a file with name `stage.credentials` or `stage.feature.credentials`
- If possible, the file/s instead of type .json could be .js or .ts, so that it could read the property values from ENV variables (`process.env`) 

Any of the solutions would work for me! Thank you!

**Comment by Arthy000** [comment]
Hi @kabomi

I like that file idea, I'll try it tomorrow but I think it shouldn't be too hard

**Comment by Arthy000** [comment]
@kabomi just pushed a branch with the changes as discussed. You can check the example I added. I'll leave you a few days to try it if you want. Merge and publish are coming but I still need to write some documentation :D

**Comment by kabomi** [comment]
Cool @Arthy000 I will test it and give you feedback. Awesome!

**Comment by kabomi** [comment]
Hey @Arthy000,
I had some holidays last week. I'd test it and IMO it works perfectly. Thanks for your efforts!
