### ISSUE TITLE
@cucumber/cucumber@8 not supported

### ISSUE THREAD

**Issue by mokone91** [Arthy000/gherkin-testcafe#77]
Hi!

Seems @cucumber/cucumber@8 not supported yet, did you plan to handle this update? 

Thanks!

**Comment by Arthy000** [comment]
Hi @mokone91 

I didn't know version 8 was released. 
It's been updated a few times already so when it looks stable I'll handle it.

Do you need it soon?

**Comment by mokone91** [comment]
Thanks for quick respose! I'll wait as long as it takes) we happy to use @7 while it supported.
I will keep issue subscrioption if you do not close it)
