### ISSUE TITLE
New Gherkin reporter throwing Exception "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by kabomi** [Arthy000/gherkin-testcafe#89]
Hi @Arthy000,

I'm trying to use your new reporters and I'm not able to make them to work.

<img width="677" alt="grafik" src="https://user-images.githubusercontent.com/3160460/172380860-df12c2d2-3724-426e-9ac6-8c06dae32ac9.png">

It looks like this line is failing across several report files (e.g. gtc-reporter-list.js:75):
```typescript
meta.steps
      .map((step) => keywords[step.type].concat(step.text))
```

As you can see on the Screenshot, I'm printing the content of meta. It is supposed to have steps with a property 'type' with either of the keys contained here: `{ Context: 'Given ', Action: 'When ', Outcome: 'Then ' }`. But I'm getting `undefined`

This is how it looks my step code:

```typescript
import { Before, Given, Then, When } from '@cucumber/cucumber';
...
Then(/^a field helper text message is shown with the text "(.+)"$/, async (test, [message]) => {
    await t.expect(await activityPage.getHelperErrorMessageFrom('field-selection')).contains(message);
});
```

package.json relevant dependencies:

"@cucumber/cucumber-expressions": "^15.2.0",
"@cucumber/cucumber": "8.2.2",
"testcafe": "~1.19.0"
"testcafe-reporter-cucumber-json": "6.3.0",

Command that I'm executing:
`gherkin-testcafe chrome e2e/**/*.steps.ts e2e/features/**/*.feature --debug-on-fail -r gtc-reporter-list,cucumber-json:.cucumber-stdout-ignore --config-file .testcaferc.local.json --tags @List,@Details,@Filter,@Create,@Edit,@Error,@Translation`

I've tried to use only one reporter (via command line  -r gtc-reporter-list) but same error dropped.

I've also tried to use the standard reporter (no command line -r argument) but same error dropped.

Any ideas?

Thanks

**Comment by Arthy000** [comment]
Hi @kabomi 
You are the second one to get this but I don't see how it could be, because the `type` value comes straight from the gherkin compiler provided by Cucumber.

Could you show me your Feature file too? Maybe there's something there.

Meanwhile you can use `spec` instead of the custom reporter by setting `-r spec` in the CLI (or `runner.reporter("spec")` if you're using the API)

**Comment by Arthy000** [comment]
The new version I just released will fix the issue, but you will have no information about the type of step because the gherkin compiler returns undefined, so I'm keeping this ticket open to investigate that

**Comment by Arthy000** [comment]
Forgot to add the fix to all the reporters, so version 5.4.2 it is

**Comment by kabomi** [comment]
I tested version 5.4.2 and now it works 👍 
<img width="913" alt="grafik" src="https://user-images.githubusercontent.com/3160460/172827301-4ecdfa5d-1d16-49eb-a3a7-424b6a958c20.png">

P.S. It looks that there is a break-line missing between the Feature description and the first step description

**Comment by Arthy000** [comment]
Indeed, will fix that in next version
