### ISSUE TITLE
Feature: Add used tags to the meta information

### ISSUE THREAD

**Issue by eisenreich** [Arthy000/gherkin-testcafe#9]
For each scenario I add a tag to be able to exclude them in the test pipeline if some of them is flaky.

When now a error happens in the pipeline I always have to compare the whole string (name of the scenario) to find the appropriate test in the source code and retrieve the tag. If I use some variables, then it gets even harder.

What would help me a lot is, if the tags of a test case are added to a meta tag like: `tags` and the value is all meta tags concatenated like `@TAG1,@TAG2`. 

Ref.: https://devexpress.github.io/testcafe/documentation/reference/test-api/fixture/meta.html

**Comment by Arthy000** [comment]
Hello,

Would it work for you if the "tags" metadata was an array instead of a string of concatenated tags ?
`[ "@TAG1", "@TAG2" ]`

**Comment by eisenreich** [comment]
Hello,

if I understood the doc right, then in this object should only be a string placed:
![image](https://user-images.githubusercontent.com/12513137/98258878-ac7c4680-1f81-11eb-9112-67c0064d90ea.png)

**Comment by Arthy000** [comment]
True, my bad :D 

Could you please provide an example of what you are trying to achieve, so I can test my changes?

**Comment by Arthy000** [comment]
@eisenreich would you rather test the changes yourself? You can pull the branch and use it by changing the dependency to gherkin-testcafe in your package.json

**Comment by eisenreich** [comment]
I added the changes from https://github.com/Arthy000/gherkin-testcafe/commit/08c4cd268cfbb508e8b2a151280bbe0c70cc096c manually and it works as expected.

Thank you very much and happy new year! 🎉
