### ISSUE TITLE
Newest working combination of NPM packages

### ISSUE THREAD

**Issue by csurfleet** [Arthy000/gherkin-testcafe#94]
I've currently got my project at these package versions:
gherkin-testcafe: ^5.0.0
testcafe: ^1.13.0
cucumber/cucumber: ^7.0.0

At this version everything works, but I can't find any later versions of the packages which do not give me this error:
`The "from" argument must be of type string. Received undefined`

I've tried updating all packages to their latest, and I've tried upping individual ones slowly, nothing I can find works. I'm now quite far behind on testcafe version so obviously I need to identify an upgrade path. A matrix of supported combinations would be really useful

**Comment by Arthy000** [comment]
Hi @csurfleet,

I've thought of creating a compatibility matrix, but recently I felt like properly maintaining the peer dependencies was easier.
If you use yarn, it'll raise warnings as soon as one of those dependencies isn't properly matched. IDK if NPM does the same though.

At the moment, the current version (5.4.3) has the following:
```json
"peerDependencies": {
    "@cucumber/cucumber": "^8.0.0",
    "@cucumber/cucumber-expressions": "^15.0.0",
    "testcafe": "~1.18.0"
}
```
This had been tested at the time of publication.

Switching from cucumber 7 to cucumber 8 was done in version 5.1.0, which in retrospect was probably not the best move (should have been version 6.0.0 instead)

If the issue keeps ocurring even with matching versions, something else that might work is deleting your node_modules to make sure everything is installed as it should.

**Comment by csurfleet** [comment]
Thanks Arthy! Thats worked for me now. I'll have a look at moving from npm to yarn if it will help with package synching thanks for the tip :)
